repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: detect-private-key

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.19.1
    hooks:
      - id: pyupgrade
        args: ["--py39-plus"]

  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.14.1
    hooks:
      - id: mypy
        additional_dependencies: ["types-requests", "types-PyYAML"]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.10
    hooks:
      - id: bandit
        args: ["-c", "pyproject.toml"]

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.22.0
    hooks:
      - id: gitleaks
        args: ["protect", "--staged", "--config", ".gitleaks.toml", "--verbose"]

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args: ["--fail-under=0"]
      - id: vulture
        name: vulture
        entry: vulture
        language: system
        pass_filenames: false
        args: ["."]
      - id: semgrep
        name: semgrep
        entry: semgrep
        language: system
        pass_filenames: false
        args: ["--config", ".semgrep.yml", "--error"]
      - id: pip-audit
        name: pip-audit
        entry: pip-audit
        language: system
        pass_filenames: false
        args:
          - "-r"
          - "requirements.txt"
          - "-r"
          - "requirements-dev.txt"
          - "--ignore-vuln"
          - "GHSA-rrmf-rvhw-rf47"
          - "--ignore-vuln"
          - "PYSEC-2025-217"
          - "--ignore-vuln"
          - "GHSA-69w3-r845-3855"
