stages:
  - security

gitleaks_scan:
  stage: security
  image:
    name: zricethezav/gitleaks:latest
    entrypoint: [""]
  script:
    - gitleaks detect --source . --verbose

pip_audit:
  stage: security
  image: python:3.11
  before_script:
    - pip install pip-audit
  script:
    - pip-audit

bandit_scan:
  stage: security
  image: python:3.11
  before_script:
    - pip install bandit
  script:
    - bandit -r .